#!/usr/bin/env bash
#This script that displays:

#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
# Function to handle SIGTERM signal

function sigterm_handler() {
    echo "I am invincible!!!"
}
trap 'sigterm_handler' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

